      - name: Free Disk Space & Add Swap
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo swapoff -a || true
          sudo rm -f /swapfile
          sudo dd if=/dev/zero of=/swapfile bs=1M count=4096 status=progress
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          
